### ISSUE TITLE
UltraNest support

### ISSUE THREAD

**Issue by JohannesBuchner** [xpsi-group/xpsi#13]
Would you be interested to add support for https://johannesbuchner.github.io/UltraNest/ ?
The interface should be very similar to pymultinest.

UltraNest is a very reliable tuning-parameter-free algorithm. I have published some examples where the UltraNest algorithm is unbiased while pymultinest gives a different answer. UltraNest is a pure-python package and very easy to install with pip or conda.

UltraNest also supports resuming from disk and MPI parallelisation, if that is useful to you.

**Comment by ThomasEdwardRiley** [comment]
Thanks, Johannes! We will try to find time to add support for UltraNest in the second half of 2021.

**Comment by drannawatts** [comment]
So when we said we would do this by 2021 @JohannesBuchner we apparently meant 2023 ;-)   @MHoogkamer is now on the case, we'll let you know how it goes (and we may have questions....).

**Comment by JohannesBuchner** [comment]
The fifth half of 2021 ;)
