### ISSUE TITLE
Display credible intervals for multiple models in corner plots

### ISSUE THREAD

**Issue by Basdorsman** [xpsi-group/xpsi#141]
NOT FOR HACKWEEK

**Comment by thjsal** [comment]
To clarify, if I understood correctly, the idea here is to allow post-processing to be run parallel to make it faster? Or to add more plot-type examples in the tutorial? The latter was already done for the v2.0.0.

**Comment by yveskini** [comment]
@thjsal,
The objective is to be able to display credible intervals for several available models, rather than limiting it to just multiple IDs. I have successfully implemented this on my local git; however, my local is somewhat too disorganized to push it.

**Comment by thjsal** [comment]
Thanks for clarifying. It sounds sounds good. I'll then re-label this issue, since this is not only about documentation or about the tutorial.
