### ISSUE TITLE
Hard bounds for temperature too restrictive for hot neutron stars

### ISSUE THREAD

**Issue by thjsal** [xpsi-group/xpsi#168]
The default hard upper limit for the temperatures should be increased from the current 7.0 if want to apply X-PSI for hot (e.g. bursting) neutron stars (at least if want to avoid making customized scripts for Hotregion and Elsewhere classes). 

Tempretature should be increased from 7.0 to 7.6 (or other suggestions @yveskini ?), here:
https://github.com/xpsi-group/xpsi/blob/c19e1a8d24799ddcdce5eea5e2f25738f61e5f00/xpsi/HotRegion.py#L441
https://github.com/xpsi-group/xpsi/blob/c19e1a8d24799ddcdce5eea5e2f25738f61e5f00/xpsi/HotRegion.py#L451
https://github.com/xpsi-group/xpsi/blob/c19e1a8d24799ddcdce5eea5e2f25738f61e5f00/xpsi/Everywhere.py#L145
and here
https://github.com/xpsi-group/xpsi/blob/c19e1a8d24799ddcdce5eea5e2f25738f61e5f00/xpsi/Elsewhere.py#L103.

**Comment by yveskini** [comment]
7.6 will do! I hardly see a model going beyond ~3.5 keV. My current bound is a bit higher but I'm using 7.6 during inference!

**Comment by sguillot** [comment]
If it's not there already, I suggest adding in a comment somewhere either in `hotregion.py`, `everywhere.py` or `elsewhere.py`, or maybe in the examples/tutorials,  to insist that :
- the surface emission model need to be defined up to the strict_bounds
- the strict_bounds need to be more restrictive in the custom hot regions/photosphere, etc...

**Comment by thjsal** [comment]
Good suggestion @sguillot . Usually, we anyway re-define the bounds to be more restrictive than the hard bounds, when creating e.g. the HotRegion object in the main script.
