### ISSUE TITLE
Use standard GetDist and NestCheck (or convert customised versions for Python3)

### ISSUE THREAD

**Issue by thjsal** [xpsi-group/xpsi#170]
Currently we use the customzied versions of GetDist and NestCheck packages in postprocessing:
https://github.com/ThomasEdwardRiley/getdist/tree/customisation
https://github.com/ThomasEdwardRiley/nestcheck/tree/feature/getdist_kde

For Python3 version, these should be updated (need a new fork?), or we should modify X-PSI to survive without them being customized.

**Comment by thjsal** [comment]
For example, if using a matplotlib version that is not too old for Python3, I get this error:

```
plots.py:10, in <module>
      7 import six
      8 import warnings
---> 10 matplotlib.use('Agg', warn=False)
     11 from matplotlib import cm, rcParams
     12 import matplotlib.pyplot as plt

TypeError: use() got an unexpected keyword argument 'warn'
```

**Comment by dhuppenkothen** [comment]
What is actually different in those versions from the official packages? Is there some way we could make xpsi use the actual packages? That would probably be less fragile in the long run.

**Comment by thjsal** [comment]
I am not very familiar with these customizations but according to Riley+2019 paper (footnotes 90 and 91) this GetDist version has some minor plotting customization, and the NestCheck version is customized to support the use of GetDist KDE. 

I don't remember exactly which things break if using the official packages, but at least some functionalities in X-PSI post-processing used to result in errors if not using these versions. That could be checked again still.

**Comment by thjsal** [comment]
So the plan is now to update X-PSI so that it could use the standard NestCheck and GetDist packages when moving to Python3. 

The first problem that encounters is related to file namings, giving e.g.
`FileNotFoundError: ./Outputs/ST_live_1000_eff_0.3_seed0_transformed-dead-birth.txt not found.
` ,
when using the standard NestCheck (and running the PostProcessing example in https://github.com/xpsi-group/xpsi/blob/main/examples/examples_fast/Postprocessing.ipynb). The file name that X-PSI produces ends with `transformeddead-birth.txt`.  I did not test it yet, but might be solved by changing how filenames are appended in https://github.com/xpsi-group/xpsi/blob/main/xpsi/PostProcessing/_backends.py for transformed parameters.

**Comment by thjsal** [comment]
Okay, seems like the solution for this problem is just to replace                        
` _np.savetxt(filerootpath + ext, transformed)`
 with
`_np.savetxt(filerootpath + "-" + ext, transformed)`
here: https://github.com/xpsi-group/xpsi/blob/e6f9f2857ffd7ec7dff00a68e0a47f8859750ce5/xpsi/PostProcessing/_backends.py#L90

**Comment by thjsal** [comment]
The next occuring error  (`TypeError: getdist.plots.GetDistPlotter.plot_1d() got multiple values for keyword argument 'no_zero'`)is fixed by replacing some kwargs with args:
```

        if isinstance(normalize, bool):
            diag1d_kwargs = {'normalized': normalize}
        if isinstance(no_zero, bool):
            no_zero1 = no_zero
        else:
            no_zero1 = True
        #    diag1d_kwargs['no_zero'] = no_zero
        if isinstance(no_ylabel, bool):
            #diag1d_kwargs['no_ylabel'] = no_ylabel
            no_ylabel1 = no_ylabel
        else:
             no_ylabel1 = True        
        if isinstance(no_ytick, bool):        
            #diag1d_kwargs['no_ytick'] = no_ytick
            no_ytick1 = no_ytick
        else:
             no_ytick1 = True            
        plotter.triangle_plot(getdist_bcknds,
                               legend_labels = legend_labels,
                               params = self.params.names,
                               filled = filled,
                               legend_loc = legend_loc,
                               line_args = line_args,
                               contour_args = contour_args,
                               no_zero = no_zero1,
                               no_ylabel = no_ylabel1,
                               no_ytick = no_ytick1,
                               diag1d_kwargs = diag1d_kwargs,
                               **kwargs)
```
here: https://github.com/xpsi-group/xpsi/blob/e6f9f2857ffd7ec7dff00a68e0a47f8859750ce5/xpsi/PostProcessing/_corner.py#L556

**Comment by thjsal** [comment]
The next error in the example PostProcessing script is `NameError: name 'getdist_kde' is not defined` coming from here https://github.com/xpsi-group/xpsi/blob/e6f9f2857ffd7ec7dff00a68e0a47f8859750ce5/xpsi/PostProcessing/_corner.py#L807 

It is raised because this `getdist_kde` function only exists in Tom's customized nestcheck. The error can be avoided by using the existing `weighted_1d_gaussian_kde` function of nestcheck instead (this is probably a bug that should be already there in the current X-PSI version, since elsewhere as well that function is used as a replacement if `getdist_kde` is not found):

```
                    try:
                        p = getdist_kde(x[where], x, w_rel,
                                        ranges=[posterior.bounds[name]],
                                        idx=0,
                                        normalize=normalize,
                                        settings=run.kde_settings)
                    except:
                        p = weighted_1d_gaussian_kde(x[where], x, w_rel)   
```

However, if we want to still use the `getdist_kde` (that seem to result e.g. in slightly different KL-divergence, but not much), that function probably needs to be transformed from Tom's nestcheck to X-PSI.

**Comment by thjsal** [comment]
The next error is `NameError: name 'np_' is not defined` coming from the line with `self.val_cred.append([np_.float(_f % _qs[0]),np_.float(_f % _qs[1]),np_.float(_f % _qs[2])])` in the Python3 branch of `_corner.py`. That is fixed by adding `import numpy as np_` in the beginning of the file. Apparently, this line was omitted when merging the main branch with the Python3 branch at some point.

**Comment by thjsal** [comment]
After this fix, a lot of corner plot are produced in the PostProcessing example, but trying to plot the true values with crosshairs raises the following error:
`TypeError: 'ValuesView' object is not an iterator`
This is caused by this line of the code:
https://github.com/xpsi-group/xpsi/blob/a6b6db29b1d3cd6c30c1a0912f593e758e8febfb/xpsi/PostProcessing/_corner.py#L1135
I guess this is probably related to the conversion from Python2 to Python3 rather than different NestCheck/GetDist packages used.

**Comment by thjsal** [comment]
Those problems that are already solved are now included in the above pull request from a new branch to the Python3 branch of X-PSI.

**Comment by thjsal** [comment]
The issue mentioned above was fixed by changing  `spine = next(plotter.subplots[0,0].spines.values())`  to  `spine = next(iter(plotter.subplots[0,0].spines.values()))`. The old python2 version had there `itervalues()`, and apparently, the suggested solution to replace it just by `values()` was not enough.

**Comment by thjsal** [comment]
This and a fix to save the figures of post-processing were pushed to the pull request. The example post-processing script still fails when trying to plot residual plots. It gives 

```
File ~/anaconda2/envs/xpsi_py3/lib/python3.10/site-packages/xpsi-1.2.0-py3.10-linux-x86_64.egg/xpsi/PostProcessing/_residual.py:148, in ResidualPlot._add_data(self)
    145 except AttributeError:
    146     self._set_vminmax()
--> 148 data = self._ax_data.pcolormesh(self._signal.data.phases,
    149                                 self._signal.data.channels,
    150                                 self._signal.data.counts/2.0,
    151                                 cmap = cm.get_cmap(self._data_cmap),
    152                                 vmin = self._vmin,
    153                                 vmax = self._vmax,
    154                                 linewidth = 0,
    155                                 rasterized = self._rasterized)
    156 data.set_edgecolor('face')
    158 data = self._ax_data.pcolormesh(self._signal.data.phases + 1.0,
    159                                 self._signal.data.channels,
    160                                 self._signal.data.counts/2.0,
   (...)
    164                                 linewidth = 0,
    165                                 rasterized = self._rasterized)

File ~/anaconda2/envs/xpsi_py3/lib/python3.10/site-packages/matplotlib/__init__.py:1412, in _preprocess_data.<locals>.inner(ax, data, *args, **kwargs)
   1409 @functools.wraps(func)
   1410 def inner(ax, *args, data=None, **kwargs):
   1411     if data is None:
-> 1412         return func(ax, *map(sanitize_sequence, args), **kwargs)
   1414     bound = new_sig.bind(ax, *args, **kwargs)
   1415     auto_label = (bound.arguments.get(label_namer)
   1416                   or bound.kwargs.get(label_namer))

File ~/anaconda2/envs/xpsi_py3/lib/python3.10/site-packages/matplotlib/axes/_axes.py:6058, in Axes.pcolormesh(self, alpha, norm, cmap, vmin, vmax, shading, antialiased, *args, **kwargs)
   6055 shading = shading.lower()
   6056 kwargs.setdefault('edgecolors', 'none')
-> 6058 X, Y, C, shading = self._pcolorargs('pcolormesh', *args,
   6059                                     shading=shading, kwargs=kwargs)
   6060 coords = np.stack([X, Y], axis=-1)
   6061 # convert to one dimensional array

File ~/anaconda2/envs/xpsi_py3/lib/python3.10/site-packages/matplotlib/axes/_axes.py:5568, in Axes._pcolorargs(self, funcname, shading, *args, **kwargs)
   5566 if shading == 'flat':
   5567     if (Nx, Ny) != (ncols + 1, nrows + 1):
-> 5568         raise TypeError('Dimensions of C %s are incompatible with'
   5569                         ' X (%d) and/or Y (%d); see help(%s)' % (
   5570                             C.shape, Nx, Ny, funcname))
   5571 else:    # ['nearest', 'gouraud']:
   5572     if (Nx, Ny) != (ncols, nrows):

TypeError: Dimensions of C (291, 32) are incompatible with X (33) and/or Y (291); see help(pcolormesh)
```

This error can be fixed by providing a phase-array reduced by the last element to the `pcolormesh `function. The resulting residual plot is, however, then not identical to the original.

**Comment by thjsal** [comment]
However, adding one extra dummy channel for the channel array, I get exactly same as before (except the old one having more y-axis tick labels):
![py3_v2](https://user-images.githubusercontent.com/16220573/212778779-af35e320-5790-4c92-910d-d7c65d394986.png)

This is the old produced using python2:
![py2_old](https://user-images.githubusercontent.com/16220573/212778781-91ce5b4a-43f1-4ac4-a3ca-afc1e965bfe6.png)
the same figure as before.

This is would be the new using python3 if reducing the phase array, instead of increasing an extra element to the channel array (the lowest bin in channels is centered at the channel=10 line, which actually seems more correct to me):
![py3](https://user-images.githubusercontent.com/16220573/212778780-46ca5bcb-7967-4bf4-b6f3-b6f0c82d1a76.png)

**Comment by thjsal** [comment]
The problem with residual plot reported above is now fixed in the branch by using the channel edges and changing also the lower limit of y-axis to correspond to the lowest energy channel edge (9.5 in this case).
