### ISSUE TITLE
Re-run all tutorials in Py3

### ISSUE THREAD

**Issue by sguillot** [xpsi-group/xpsi#204]

**Comment by sguillot** [comment]
The "Modeling (without statistics)" works fine, but because of some difficulties with ffmpeg installation, I recommend removing the mentions to the MovieWriter and let matplolib choose the default:
``` 
ani.save(filename, writer = 'ffmpeg', 
         dpi = dpi, fps = fps, bitrate = bitrate,
         extra_args=['-vcodec', 'libx264'])
```
becomes
```
ani.save(filename,
         dpi = dpi, fps = fps, bitrate = bitrate,)
```

It would be nice to check that this works too on other machine (linux, etc..)

**Comment by yveskini** [comment]
It works on Linux! Checked

**Comment by sguillot** [comment]
- Modelling notebook OK (some modifications pushed)
- Modelling without statistics notebook OK (some modification pushed)
- Instrument synergy notebook (some modifications pushed)
- Hot region complexity notebook OK (no changes)

**Comment by sguillot** [comment]
- Surface radiation field tools notebook OK (no changes)

**Comment by thjsal** [comment]
Done in #256 .
