### ISSUE TITLE
Clarify the extensions requirements in the tutorials

### ISSUE THREAD

**Issue by sguillot** [xpsi-group/xpsi#212]
if XPSI needs to be compiled with specific extensions, this needs to be visible, in BOLD, BLINKING, UNDERLINED font.

**Comment by thjsal** [comment]
After merging this pull request: #303, there is only one extension change (requiring re-installing X-PSI) that needs to be done in one of the tutorials (Modeling without statistics). However, that will now be mentioned boldfaced at the beginning of the tutorial. So I suggest closing this issue when that pull request gets merged.
