### ISSUE TITLE
Py3 X-PSI doesn't display wrong atmosphere extension message on terminal when Jupyter notebook crashes

### ISSUE THREAD

**Issue by DevarshiChoudhury** [xpsi-group/xpsi#218]

**Comment by thjsal** [comment]
As I mentioned in slack, I indeed think that Python3 version of Jupyter does not actually seem to produce all the prints that should happen before the kernel dies (it misses the latest of them). I guess a better way would be to properly handle the error, instead of letting the code crash (=kernel dying) and trying to print messages before that.

**Comment by thjsal** [comment]
However, it is not very clear to me how to do it in Cython.

**Comment by thjsal** [comment]
I tried the following in the numerical.pyx, and it indeed prevents segmentation fault from happening if running from the terminal (it just finishes then with the error message). But it does not help the notebook, since there the kernel still dies. 

```
from libc.math cimport M_PI, sqrt, sin, cos, acos, log10, pow, exp, fabs
from libc.stdio cimport printf, fopen, fclose, fread, FILE, fprintf, stderr
from GSL cimport gsl_isnan, gsl_isinf
from libc.stdlib cimport malloc, free, exit, EXIT_FAILURE
....
if preloaded == NULL :
  fprintf(stderr, "ERROR: The numerical atmosphere data were not preloaded, which are required by this extension.\n")
  exit(EXIT_FAILURE)
```

**Comment by thjsal** [comment]
This problem is now fixed as a part of the pull request linked above. There atmosphere extension is chosen without re-installing X-PSI, and thus error can be raised already in the Python level, and jupyter notebook also gives the correct error message.

**Comment by sguillot** [comment]
I wouldn't mark the issue as completed as long as the PR has not been merged. No?

**Comment by DevarshiChoudhury** [comment]
I closed the issue under the assumption that new issues that pop up after merging the PR @thjsal mentioned would be addressed as new issues, and not this anymore. But it's true that users will face the issue until the PR is merged, and new users could look at this being an open issue and figure out their ways around it. I am fine with re-opening the issue if everyone thinks that makes more sense
