### ISSUE TITLE
Link postprocessing notebook between examples/ and docs/source/

### ISSUE THREAD

**Issue by sguillot** [xpsi-group/xpsi#232]

**Comment by sguillot** [comment]
PR #256

**Comment by thjsal** [comment]
I tried again to link the post-processing script from examples to the documentation, but I only managed to do it for a *.rst or *.md file, using the approach explained here: https://stackoverflow.com/questions/10199233/can-sphinx-link-to-documents-that-are-not-located-in-directories-below-the-root

For a Jupyter notebook this did not apparently work (the compilation got always stuck without any error messages when trying). Thus, we agreed with @yveskini to just start maintaining this script under the `docs/source` folder for simplicity.  This issue will be closed when the linked pull request is merged.
