### ISSUE TITLE
emcee compatibility

### ISSUE THREAD

**Issue by sguillot** [xpsi-group/xpsi#26]
`emcee` has been upgraded to version 3.1.1, which requires the package `autocorr`, which is not compatible with python2.7.
So it is recommended to install emcee with `pip install emcee==3.0.1`.
A note about this could be added to the installation tutorial.

**Comment by thjsal** [comment]
Seems to me that this issue is already solved, and can be closed, All the emcee instructions now mention the version that needs to be used.
