### ISSUE TITLE
Investigate why residuals are different between py2 and py3

### ISSUE THREAD

**Issue by sguillot** [xpsi-group/xpsi#260]
in tutorial notebooks `Modeling.ipynb` and `Instrument_synergy.ipynb`

**Comment by thjsal** [comment]
Problem solved! It seems that in the Py3 version, GSL seed was still not fixed properly, so we did not get the exact same result. First of all, I instructed you to give gsl_seed input parameter to a wrong function. Secondly, there is also a bug in the seed implementation which prevents fixing the seed to zero from working (and fixing it to zero is what we need here). I'll create a branch to make corrections to the synthesise functions and the tutorials. I already tested that I can get same residuals with Py3 as with Py2.
