### ISSUE TITLE
`np.int` deprecated as of `numpy 1.24.0` causing imports to crash

### ISSUE THREAD

**Issue by sguillot** [xpsi-group/xpsi#271]
Error:
![numpy](https://user-images.githubusercontent.com/22171129/217248054-66c80fd7-cbd1-4ce3-8bd6-d6cc63bad394.png)

Short term solution: adding a numpy requirement in the documentation

Long term solution: replacing `np.int` by `np.int32` or `np.int64`

**Comment by dhuppenkothen** [comment]
I think we should fix this ASAP, rather than requiring an old version of numpy. :)

**Comment by sguillot** [comment]
Agreed.  There seems to be only 1 occurence of `np.int`, in `Data.py`.  
All others are already `np.int32`.
