### ISSUE TITLE
Update Python3 installation instructions

### ISSUE THREAD

**Issue by thjsal** [xpsi-group/xpsi#277]
Python3 installation instructions should be updated to use the newest MultiNest (https://github.com/farhanferoz/MultiNest instead of https://github.com/JohannesBuchner/MultiNest), as in the Python2 version. Check also if other updates need to be done.

**Comment by sguillot** [comment]
Also, it used to be that we had to go into `cd MultiNest/MultiNest_v3.12_CMake`.
Is it still the case with the Farhanferoz version ?

**Comment by thjsal** [comment]
Yes, I think that Farhanferoz version (with CMake) is still correct to be used.

**Comment by sguillot** [comment]
In this case the installation instruction of MultiNest (py3 version of the doc) needs to be updated as well. something like this worked for me:
```
git clone https://github.com/farhanferoz/MultiNest
cd MultiNest/MultiNest_v3.12_CMake/multinest
mkdir build
cd build
cmake ..
make
```
