### ISSUE TITLE
Install instruction for pymultinest on Mac

### ISSUE THREAD

**Issue by sguillot** [xpsi-group/xpsi#283]
For me, installing `pymultinest` with `conda` also force installs `multinest` which then doesn't work for `pymultinest`.

Instead, I installed pymultinest by cloning and installing. The following instruction should probably be added for the Mac installation instruction. 
```
git clone https://github.com/JohannesBuchner/PyMultiNest.git ./pymultinest
cd pymultinest
python install setup.py
```

**Comment by thjsal** [comment]
I will add this to the general instructions since probably this is what needs to be done for other than Mac cases as well.
