### ISSUE TITLE
Change is_secondary in Hot_region_complexity

### ISSUE THREAD

**Issue by daspushpita** [xpsi-group/xpsi#291]
https://github.com/xpsi-group/xpsi/blob/ace8ec39e2ed7f59bd84ce99ec2014b9121abfe8/docs/source/Hot_region_complexity.ipynb

**Comment by thjsal** [comment]
And what is the reason it needs to be changed?

**Comment by daspushpita** [comment]
Because it is deprecated I guess?

**Comment by thjsal** [comment]
I don't think it is deprecated yet. I thought it just that we want to deprecate it.

**Comment by thjsal** [comment]
Okay, I see in the comment string (in `HotRegion.py`) that this `is_secondary` is indeed deprecated in the sense that it has exactly the same effect as if using `is_antiphased` keyword argument. But it principle, it should still work as it is meant to work, right?

**Comment by thjsal** [comment]
I think it is fine to close this issue, since it is essentially a duplicate of the issues #296 and #323.
