### ISSUE TITLE
Check tutorials/notebook for mentions of `antiphase=True` or `-0.5` phase added in Priors

### ISSUE THREAD

**Issue by sguillot** [xpsi-group/xpsi#296]

**Comment by thjsal** [comment]
Usage of them looks consistent in the Tutorials for me. I.e., always when using `antiphase=True` (or `is_secondary=True`), we have -0.5 added in the phase in the `CustomPrior.py`. 

Are you suggesting to change it everywhere so that `antiphase=False` and remove the 0.5 from priors?

**Comment by sguillot** [comment]
Yes. This was discussed during the hackweek to discard the (confused) `-0.5` prior.

**Comment by thjsal** [comment]
Okay, sounds a good idea! It will then also solve this issue #291.

**Comment by thjsal** [comment]
I think it is fine to close this issue, since it is essentially a duplicate (or overlaps very strongly) with the issue #323 .
