### ISSUE TITLE
Bug when defining a `param_plot_lims` in a Corner plot post-processing

### ISSUE THREAD

**Issue by sguillot** [xpsi-group/xpsi#301]
When I defined a `param_plot_lims` in a Corner plot, I get a warning:
```
WARNING:root:tight_gap_fraction is removed and will be ignored
```
and a TypeError:
```
File ~/...../_corner.py:578, in CornerPlotter._plot_triangle(...)
--> 578 gap_wanted = width * plotter.settings.tight_gap_fraction
TypeError: unsupported operand type(s) for *: 'float' and 'NoneType'
```
because apparently `tight_gap_fraction` is None somwhere. I can't figure out how to define this value. But also I think the `tight_gap_fraction` (from GetDist) used in the triangle PostProcessing plot has actually been deprecated:
https://getdist.readthedocs.io/en/latest/search.html?q=tight_gap_fraction&check_keywords=yes&area=default

**Comment by thjsal** [comment]
Does this error occur when you try to plot something you did not try before? This could be maybe a problem with using now the latest GetDist with X-PSI v2.0, for one of the many plot options that were not tested yet. Can give more details how to re-produce this?

**Comment by sguillot** [comment]
When plotting a simple corner plot (pp.plot() in a PostProcessing notebook), everything works fine with `param_plot_lims={}`, and the x- and y- ranges of all plots are set up automatically.  But if I want to widen these ranges, I defined
```  param_plot_lims={'radius':(10,16), 'mass':(1.0,2.5),},
,

**Comment by yveskini** [comment]
@sguillot Indeed **tight_gap_fraction**  is depreciated in the new version of getdist that we are using. However, in previous versions, the value was set to 0.13. (tight_gap_fraction = 0.13), So it makes more sense to use that value as default in xpsi.

**Comment by yveskini** [comment]
I think just hard-coding the 0.13 will be fine. There is also a line somewhere below where this value is been used. So changing that will also be necessary.

**Comment by thjsal** [comment]
I guess we can then introduce `tight_gap_fraction = 0.13 ` above, and then replace the following 2 occurances of `plotter.settings.tight_gap_fraction` with that:

https://github.com/xpsi-group/xpsi/blob/aaae64e3983448962a11fdd1721976a72215c0c5/xpsi/PostProcessing/_corner.py#L578

https://github.com/xpsi-group/xpsi/blob/aaae64e3983448962a11fdd1721976a72215c0c5/xpsi/PostProcessing/_corner.py#L591

I can create a branch to fix the issue.
