### ISSUE TITLE
Retrieve curves data from SpectrumPlot

### ISSUE THREAD

**Issue by ychatonnier** [xpsi-group/xpsi#302]
Is it possible to retrieve curves data (spectrum and background) calculated from SpectrumPlot ?
Or is it possible to plot 2 spectrums calculated from 2 differents run on the same figure ?

**Comment by thjsal** [comment]
I think retrieving that might require some customization of the SpectrumPlot class. I am not sure about the second question, but I think you could try that, but it might just end up producing different plots for all the runs.

**Comment by ychatonnier** [comment]
I already looked at the class to modify it but I didn't know where the curves were created, I was hoping someone had done this before. And for the second part, yes with two differents runs in input i can only plot the output of one run or the other but not the two one the same figure.
thank you for your response

**Comment by drannawatts** [comment]
No one seems to need this any more so we are closing.
