### ISSUE TITLE
No API for CornerPlotter showing on documentation page

### ISSUE THREAD

**Issue by sguillot** [xpsi-group/xpsi#306]
There are some examples of `CornerPlotter` in the tutorials, but the full API does not show on this page: https://xpsi-group.github.io/xpsi/postprocessing.html

**Comment by thjsal** [comment]
I think that page mostly shows the docstrings for all the CornerPlotter methods. Is there something specific that you find missing there?

Or you were expecting to see more examples of how to use the methods, as in here: https://xpsi-group.github.io/xpsi/Post-processing.html?

**Comment by sguillot** [comment]
```
I think that page mostly shows the docstrings for all the CornerPlotter methods. 
```
That's the thing, it doesn't show the docstring of CornerPlotter, only for `SignalPlotter`, `ResidualPlotter`, `PulsePlot`, `SpectrumPlot`

**Comment by thjsal** [comment]
I see you are right! Need to check why that is so.

**Comment by thjsal** [comment]
The Cornerplotter API actually shows up when I compile the documentation locally on my laptop. So for some reason, GitHub does not compile it in the same way.
