### ISSUE TITLE
Newly released Cython may be backward incompatible for an X-PSI installation

### ISSUE THREAD

**Issue by evertrol** [xpsi-group/xpsi#319]
Cython 3.0.0 has recently been released (July 17, 2023), and has likely backward incompatibilities with the Cython 0.2* series. Since X-PSI relies on Cython to be build afaik, this may cause build problems.

Ultimately, if there are build errors with Cython 3, it should be fixed here in the code that uses and builds Cython, so that X-PSI is forward-compatible and future-proof.

A temporary(!) work-around is to set stricter requirements for the Cython dependency in `setup.py`. So this line
```
        setup_requires = ['cython'],
```
may become
```
        setup_requires = ['cython ~= 0.23'],
```
(or whatever minimal Cython version works. 0.29 might be fine.)

To clarify, the compatible release specifier, `~= 0.23`, is similar to `>= 0.23, == 0.*`. Which you could also use if you find that clearer.

----

Aside, something similar should be the case for the NumPy dependency. There should be a minimum version requirement, *and* a maximum version requirement, for any dependency.

**Comment by thjsal** [comment]
The temporary work-around to this was done in #322 .
