### ISSUE TITLE
Remove deprecated is_secondary and set is_antiphased to False in all examples

### ISSUE THREAD

**Issue by sguillot** [xpsi-group/xpsi#323]
The `@is_secondary.setter` method of the `HotRegion` class should check that is_secondary is a boolean, and set it to `self`.  But the fonction is coded with `is_antiphased`.  Is this normal ?

```
@is_secondary.setter
def is_secondary(self, is_secondary):
    if not isinstance(is_antiphased, bool):
        raise TypeError('Use a boolean to specify whether or not the '
                        'hot region should be shifted by half a cycle.')
    else:
        self._is_antiphased = is_antiphased
```

Also, the worst part is that `is_antiphased` is undefined in this method.  see screen capture:
![capture](https://github.com/xpsi-group/xpsi/assets/22171129/3efbc046-d13f-486c-bc00-25abb8e05084)

Any thought on this ?

**Comment by DevarshiChoudhury** [comment]
`is_secondary` and `is_antiphased` are supposed to do the same thing, with the former being a deprecated argument. Looking at the screenshot, it seems that it could potentially not work as intended if both arguments don't pass the same thing. Will take a look into it today

**Comment by sguillot** [comment]
Well I'm not sure.
I think it should be fixed, or removed from the `HotRegion` if it is deprecated, no ?

**Comment by DevarshiChoudhury** [comment]
I think it was originally retained so that people running any old scripts can continue using it. Although I suppose, by now there have been so many changes since that version that it is probably better to just remove it, and have people run those scripts using the relevant X-PSI versions

**Comment by DevarshiChoudhury** [comment]
@sguillot, @thjsal if you agree with the above proposition of removing the deprecated argument, I can change all the `is_secondary` to `is_antiphased`

**Comment by sguillot** [comment]
Yes, I think so. (and all the occurence in tutorial notebooks).  I had meant to do it but never got the chance to actually do so.

At the same time, it would be good to solve #296 (and #291) if you can

**Comment by thjsal** [comment]
Removing the deprecated `is_secondary` sounds fine to me. And if I got it right, @sguillot wants also `is_antiphased` to be removed, or at least set to `False` in all our examples and analyses. Both options are fine to me. But good to then keep in mind that one of our sampled parameters is then defined differently than before, and that should be clearly noted in the papers.

**Comment by thjsal** [comment]
I removed the issue that were essentially same as this one. Just need to remember also change the CustomPrior and remove -0.5 also from there, when changing antiphase to False. 

I think for reproducing the old results, it could still be useful to keep the `is_antiphased` flag existing, but changing the default to False sounds good to me.

**Comment by Basdorsman** [comment]
Addresing this in issue #482
