### ISSUE TITLE
Deprecated use of Numpy (np.float) in post-processing corner plot 

### ISSUE THREAD

**Issue by MHoogkamer** [xpsi-group/xpsi#344]
Using the `PostProcessing.Cornerplot` gives the following issue:
```
AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20;
```
Can be solved by changing `_np.float` into `float` in line 947 in `_corner.py`

Related to #336

**Comment by thjsal** [comment]
For curiosity, what NumPy version are you using?

And I guess it is the `np_.float` in line 949 in the current [_corner.py](https://github.com/xpsi-group/xpsi/blob/57a7dcb8a902ddda5c25a75d4c99d2f97a5e6848/xpsi/PostProcessing/_corner.py#L949C1-L949C1) of the main branch.

Would you like to fix it?

**Comment by MHoogkamer** [comment]
I'm using NumPy 1.26

Yes! I made a pull request
