### ISSUE TITLE
Update publication list

### ISSUE THREAD

**Issue by drannawatts** [xpsi-group/xpsi#354]
Change Applications -> Publications (makes more sense as a title)

Add Kini et al. 2023b, Vinciguerra et al. 2023a, b as soon as final published versions are available.

**Comment by thjsal** [comment]
Also Salmi et al. 2023 (Atmosphere effects), please :).

**Comment by drannawatts** [comment]
Yikes, did we not put that on there yet either?!

**Comment by thjsal** [comment]
Is this issue now fixed and can be closed?

**Comment by drannawatts** [comment]
Might be :-D
