### ISSUE TITLE
Intervals calculated appear to be incorrect

### ISSUE THREAD

**Issue by DevarshiChoudhury** [xpsi-group/xpsi#377]
https://github.com/xpsi-group/xpsi/blob/1deb8799bfed8f5caa0452a8822cc5166fc4268a/xpsi/PostProcessing/_corner.py#L1075

Seems like the wrong quantiles are specified for interval calculation

**Comment by thjsal** [comment]
I think this is not a bug. Seems to me that in these lines the idea is to calculate all the other intervals, since having `compute_all_intervals=True` and the 68% interval was already calculated.

**Comment by DevarshiChoudhury** [comment]
I see. I was wondering if it was intentional somehow, and generally, I haven't previously seen anything wrong in post-processing, but couldn't make out immediately if this was right either and thought of just raising an issue. I will close it then
