### ISSUE TITLE
precisions argument should be an argument in load_runs?

### ISSUE THREAD

**Issue by Basdorsman** [xpsi-group/xpsi#393]
Let me know if you agree!

Currently `precisions` is an argument in `xpsi.PostProcessing.CornerPlotter.plot` that allows you to change the precision of the credible intervals of each parameter. However, I think it should be an argument in `xpsi.PostProcessing.Runs.load_runs`. 

With my suggestion, you would first (ideally optionally) define the precisions for each parameter, and then later decide with parameters you actually plot in your corner plot. Without my suggestion, you have to redefine the precisions each time you want to plot a new subset of parameters.

**Comment by thjsal** [comment]
I agree, moving it to the `load_runs` sounds like a good idea.
