### ISSUE TITLE
Incompatible code for latest `getdist` source version (1.5.4)

### ISSUE THREAD

**Issue by DevarshiChoudhury** [xpsi-group/xpsi#404]
I installed `getdist` from source via the commands:
```
git clone https://github.com/cmbant/getdist.git
pip install -e getdist/
```

The following line:
https://github.com/xpsi-group/xpsi/blob/a3fd654ca4658825253b46d563d571e766b2f855/xpsi/PostProcessing/_global_imports.py#L68
yields the error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/<home>/anaconda3/envs/xpsi_py3/lib/python3.12/site-packages/xpsi-2.2.7-py3.12-linux-x86_64.egg/xpsi/__init__.py", line 92, in <module>
    from xpsi.PostProcessing import *
  File "/<home>/anaconda3/envs/xpsi_py3/lib/python3.12/site-packages/xpsi-2.2.7-py3.12-linux-x86_64.egg/xpsi/PostProcessing/__init__.py", line 52, in <module>
    from xpsi.PostProcessing._global_imports import * # access, e.g., random_seed global
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/<home>/anaconda3/envs/xpsi_py3/lib/python3.12/site-packages/xpsi-2.2.7-py3.12-linux-x86_64.egg/xpsi/PostProcessing/_global_imports.py", line 68, in <module>
    print('Imported GetDist version: %s' % getdist.__version__)
                                           ^^^^^^^^^^^^^^^^^^^
AttributeError: module 'getdist' has no attribute '__version__'
```

and the following line:
https://github.com/xpsi-group/xpsi/blob/a3fd654ca4658825253b46d563d571e766b2f855/xpsi/PostProcessing/_global_imports.py#L71
yields the error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/<home>/anaconda3/envs/xpsi_py3/lib/python3.12/site-packages/xpsi-2.2.7-py3.12-linux-x86_64.egg/xpsi/__init__.py", line 92, in <module>
    from xpsi.PostProcessing import *
  File "/<home>/anaconda3/envs/xpsi_py3/lib/python3.12/site-packages/xpsi-2.2.7-py3.12-linux-x86_64.egg/xpsi/PostProcessing/__init__.py", line 52, in <module>
    from xpsi.PostProcessing._global_imports import * # access, e.g., random_seed global
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/<home>/anaconda3/envs/xpsi_py3/lib/python3.12/site-packages/xpsi-2.2.7-py3.12-linux-x86_64.egg/xpsi/PostProcessing/_global_imports.py", line 71, in <module>
    getdist.chains.print_load_details = False
    ^^^^^^^^^^^^^^
AttributeError: module 'getdist' has no attribute 'chains'
```

**Comment by thjsal** [comment]
Did you check that the getdist installation works with `python -m unittest getdist.tests.getdist_t`?

**Comment by thjsal** [comment]
The old way to install GetDist from source used to be
`python setup.py install`
I wonder if that would still work. Or if you use pip, would it work better if doing
`python -m pip install -e /path/to/source` (to make sure correct python version is used)?

**Comment by DevarshiChoudhury** [comment]
Yes, I had tried the unit test and it had worked just fine. Based on their current documentation I used `pip install -e /path/to/source`. I can try adding `python -m` before to check if it makes any difference but I doubt it since this is a fresh new system with only one python version as far as I am aware

**Comment by thjsal** [comment]
I still suspect something went wrong in the installation. I just installed the latest GetDist v1.5.4 as well (using the same pip command as you) and did not get these error messages. Instead, it just reports that `Imported GetDist version: 1.5.4` when importing xpsi. So it seems to me that even the latest GetDist does have attribute `__version__`.

**Comment by DevarshiChoudhury** [comment]
Thanks for the suggestion. I think there indeed might be something going wrong with my file paths which is odd though considering I've only had a single version installed. I tried running the command you suggested here as well as the original lines I marked as issues within a jupyter notebook and it executes just fine, but if I activate my virtual environment in terminal and open either python or ipython in terminal and run them, they don't work. I will close this issue since it seems to be a local problem for me then.

**Comment by thjsal** [comment]
No problem. I guess something then wrong in the virtual environment. I would try to completely remove the getdist installation from there (so that already 'import getdist' fails) and then re-install it. It may perhaps require you to manually remove some getdist-related files from your environment directory.

**Comment by DevarshiChoudhury** [comment]
I encountered this issue again while installing in another virtual Ubuntu system (Surf Research Cloud). This time I had an absolutely clean installation with only one version of getdist cloned from source and installed also using `python -m` this time, so I'm not sure where the path pointers are going wrong with getdist for the terminal based python/ipython. Checking now on jupyter if this is fine again...

**Comment by thjsal** [comment]
Could it be that there is already some pre-existing empty getdist in these systems? Or it gets somehow automatically generated when you create the environment? Maybe you would have got this exactly same if not even trying to install GetDist.

**Comment by DevarshiChoudhury** [comment]
No, the system was completely empty when I first signed in. But, yea I can't rule out yet if getdist is getting installed as a dependency for some other packages being installed (but this seems unlikely to me). The environment creation alone shouldn't affect it since I used the `basic_environment.yml` which only has a few packages in there (unless those packages install getdist for some reason which is again unlikely)

**Comment by thjsal** [comment]
I see. Quite strange indeed. I wonder if you are able to uninstall GetDist so that it cannot import it anymore at all? 

I also remember there used to be some weird issue of some environment information carried by the Mac terminal to the cluster (for Rahul in Helios, and it was solved by Martin/Evert). I am not sure though if this could be a similar case.

**Comment by DevarshiChoudhury** [comment]
Right, yea, I remember him some issue when logging in into Helios although I do not quite remember what it was about.

I will try uninstalling it and see if it still imports it. Would be strange if it does, but then indeed it would clarify the presence of more than one getdist

**Comment by thjsal** [comment]
Btw, I happened to get this same error as well, when trying to import getdist from a directory in which I had a directory called getdist (so it was just importing the directory name). I wonder if that could be the case for you too? However, I just re-installed X-PSI and GetDist and now I can again import X-PSI even in this directory.
