### ISSUE TITLE
Posterior post-processing for individual mode

### ISSUE THREAD

**Issue by lmauviard** [xpsi-group/xpsi#415]
So far, all the posterior post-processing is done by drawing samples from `*equal_weight.dat`

This can be done on individual posterior modes by getting posterior samples from `*post_separate.dat`, an output of Multinest when using multi-mode. I suggest to add a possibility to do it in post-processing with a `modes` parameter when loading runs.

**Comment by thjsal** [comment]
The pull request connected to this was not merged yet, so the issue is not yet closed?

**Comment by lmauviard** [comment]
Ups, wrong manipulation
