### ISSUE TITLE
code in examples folder is broken

### ISSUE THREAD

**Issue by dhuppenkothen** [xpsi-group/xpsi#45]
Hi all, I've been poking around XPSI, and especially I'd like to synthesize some data based on the model. I've found some code to do this in the `examples` folder, but I suspect it might be outdated? It refers to functions and classes that don't seem to exist in XPSI. Specifically, I tried running `synthesise.ipynb`, but it refers to a `synethesise` function that I can't find in the module where it's supposed to be (there are two separate functions there, and I don't know which one to use), and it also refers to a `xpsi.Pulse` module that I also can't find.

At this point I stopped trying to make it run. I think this would be worth checking/updating/adding to the official documentation?

**Comment by sguillot** [comment]
@yveskini Has this been resolved in your pull request #105  ?

**Comment by thjsal** [comment]
Has been now solved by request #105 indeed.
