### ISSUE TITLE
`PP-plot` tutorial shows up on the index tree despite no separate entry in `index.rst`

### ISSUE THREAD

**Issue by DevarshiChoudhury** [xpsi-group/xpsi#496]
`PP-plots` are only a subpart of the `postprocessing` notebook. It doesn't show up due to the markdown header listing.

**Comment by thjsal** [comment]
If I remember right, this issue might already be solved as a part of this pull request: 
https://github.com/xpsi-group/xpsi/pull/483

**Comment by DevarshiChoudhury** [comment]
I see. It hasn't been merged yet, so it still shows up in the docs. I'll link this issue to that pull request

**Comment by lmauviard** [comment]
Closed by #483
