### ISSUE TITLE
Chi2 error

### ISSUE THREAD

**Issue by lmauviard** [xpsi-group/xpsi#502]
Documentation of Chi2 has an unexisting parameter

Residuals plotting use the chi2 of the last parameter vector sample used. This is wrong and results in a wrong value being plotted.

**Comment by lmauviard** [comment]
@thjsal Can I just fix that in your current PR #499 ? There are just a few lines !

**Comment by thjsal** [comment]
Sure. Or you can fix it yourself there as well. I am only working on the Changelog now.
