### ISSUE TITLE
Create script to switch between Numerical and Blackbody

### ISSUE THREAD

**Issue by sguillot** [xpsi-group/xpsi#72]
copy files (`hot', 'elsewhere') from `surface_radiation_field/archive/' into 'surface_radiation_field' and recompile.

**Comment by Basdorsman** [comment]
We should discuss this (or discuss with Yves), since a script exists in at least my fork.

**Comment by sguillot** [comment]
Ah, thanks @Basdorsman 

I was thinking about including this into `setup.py` file as an option, since everything needs to be recompiled anyway. But I'm not too familiar with 'setup.py' configurations.
Thoughts ?

**Comment by sguillot** [comment]
Done with #102
