### ISSUE TITLE
Importance sampling documentation

### ISSUE THREAD

**Issue by drannawatts** [xpsi-group/xpsi#87]
Add documentation and possibly a tutorial on importance sampling, since we have used this some of the published X-PSI papers.

**Comment by sguillot** [comment]
@MHoogkamer this can be closed right ?

**Comment by DevarshiChoudhury** [comment]
@sguillot I don't think @MHoogkamer worked on this. I have just assigned @yveskini to this since he had mentioned he has the scripts.
