### ISSUE TITLE
Confirm whether behaviour of ST+PST priors in module generator is as expected

### ISSUE THREAD

**Issue by DevarshiChoudhury** [xpsi-group/xpsi#88]
@serenavinciguerra89 had mentioned that certain parameter vectors which ought to be allowed within ST+PST prior volume, based upon previous versions of the code and the appearance of the spots in the module generator, do not seem to be allowed by the formalism provided in the module generator. Check whether this should be so.

Discussion link:
https://xpsi-men.slack.com/archives/C02E3FG0FA5/p1650993296135859?thread_ts=1633015210.009300&cid=C02E3FG0FA5

**Comment by thjsal** [comment]
Checking that slack-thread, it seems to me that this parameter was suspected to be a problem for ST-PST:
`
p =[2.595463644164531, 11.848157917404729, 0.3325019221454726, 0.19649099366715728, -0.1876076739041842, 0.8238137631192921, 0.4007678716882901, 5.169632242144919, 0.3636868291538101, 0.7662227759721904, 0.5574691494377351, 5.5850642027179065, 0.8621177633522776, 0.5521585708455099, -0.31361117103072816, 0.8898045212698502, 2.3008345859754615]`

The suspicion was that this parameter vector would not be allowed by the module generator version of ST-PST even though it should be. But was that in the end tested or not? It was not mentioned in the thread.

**Comment by DevarshiChoudhury** [comment]
No I haven't had the chance to test it yet. Would be worth looking into before upgrading module generator to py3 version. I shall put a hackweek 2023 label to it

**Comment by thjsal** [comment]
I checked that this parameter vector passes the CustomPrior checks generated by the module generator as it should. 

Here are the modules I used (only slightly modified for testing after creating them using a ``generate.ini`` similar to that in GitHub examples):
[_auto_modules_testSTPST.zip](https://github.com/xpsi-group/xpsi/files/13207103/_auto_modules_testSTPST.zip)

The ``generate_test_STPST.ini`` and ``config_test_STPST.ini`` files are also in the attachment, and the modules can be run using the GitHub example data with ``python main.py @config_test_STPST.ini``.


Here also the plot of the allowed configuration:
![test_STPST](https://github.com/xpsi-group/xpsi/assets/16220573/fb0c25c4-d935-42d9-be4e-9fbe0b72917f)

**Comment by thjsal** [comment]
Unless someone else wants to double check that too, I would suggest to close to this issue.

**Comment by DevarshiChoudhury** [comment]
I can re-check it in the py2 version and then close the issue

**Comment by thjsal** [comment]
Do still think this is worth to check with py2 version, since that version is anyway deprecated according to X-PSI documentation? Does it matter if it works with that version or not?

**Comment by DevarshiChoudhury** [comment]
yea, I think we can just close this issue
