### ISSUE TITLE
Chi-squared calculator

### ISSUE THREAD

**Issue by drannawatts** [xpsi-group/xpsi#90]
Add a tutorial on the Chi-squared calculator (and the chi-squared calculator itself :-D )

**Comment by drannawatts** [comment]
I think this was the feature in the post-processing notebooks that computes chi-squared. Is it not?

**Comment by thjsal** [comment]
Yes, in some of them made by @serenavinciguerra89 , but the version including that have never been included in GitHub.

**Comment by thjsal** [comment]
I am not sure if those can even be found in the Zenodo repositories of our papers.

**Comment by drannawatts** [comment]
I think it's useful to have though, right? I'll modify the issue to reflect that it's a full-scale addition of everything, not just the tutorial!!
