### ISSUE TITLE
Unit tests for spacetime module

### ISSUE THREAD

**Issue by drannawatts** [xpsi-group/xpsi#97]
Try to write unit tests for the spacetime module

**Comment by sguillot** [comment]
Future work:  unit test to check the calculation of `a` and `q` in Spacetime module (following AlGendy & Morsink 2014)

**Comment by DevarshiChoudhury** [comment]
@Basdorsman with your suite of unit test additions, is this issue already addressed?

**Comment by Basdorsman** [comment]
No, I was doing hot region unit tests

**Comment by drannawatts** [comment]
Closing for now because we are too lazy to do this.
